# Classification of Different Classes of Cyber Attacks

## Abstract 

In this project, we use machine learning alogorithms to understand the intrusion detection on NSL-KDD dataset. Multiple ML algorithms like Random Forest, K-Neighbors, Support Vector Classifier and Ensemble classification are used to understand differnt classes of attacks and their significance in the data set. The accuracy of each models are compared to understand which classification model is more efficient for this dataset. 

## Introduction

In the world where technology is a part of our life or we can even say that we are a part of technology (by looking at the meracles technology is capable of doing today). Safety and privacy of a person is at the utmost importance. It is very easy for a person to leave some data behind every second he is on internet. Tracking this data has become much easier than ever before and in order to prevent, we need to understand the different kinds of attacks that possible on a person or a system.  

IT security is an important issue and much effort has been spent in the research of intrusion and insider threat detection. Many contributions have been published for processing security-related data, detecting botnets, port scans, brute force attacks and so on. All these works have in common that they require representative network-based data sets. There are many benchmark data sets that are good basis to evaluate. I have tried to understand the different class of attacks by analysing the NSL-KDD dataset.

It is very important for a person to understand the different possible attacks in order to prevent himself from being the victim of an attack.


## Goal of the Project

1. The main goal of the project is compare different methods of classification and understand which type is more effective in finding accuracy. 

### Data Source: https://www.unb.ca/cic/datasets/nsl.html

## Knowledge about NSL-KDD

NSL-KDD is a updated version of KDD cup99 data set. NSL-KDD is a data set suggested to solve some of the inherent problems of the KDD'99 data set. This data set is an effective benchmark for researchers to compare different types of Intrusion detection system (IDS) methods, build an Intrusion detection system ( Host based or Network based), doing for some experiments in Cyber security area like wise there is so many advantages. And also there are lot of data sets ( ADFA-ID, ISCX-UNB etc) which use in this field. 

**Reference**
1. https://www.unb.ca/cic/datasets/nsl.html#:~:text=NSL%2DKDD%20dataset,are%20mentioned%20in%20%5B1%5D.&text=Furthermore%2C%20the%20number%20of%20records,and%20test%20sets%20are%20reasonable.

2. https://medium.com/@lasithahiranya/did-you-know-the-famous-data-set-called-nsl-kdd-293b39420c74

3. https://arxiv.org/pdf/1903.02460.pdf

**Importing Libraries and Data sets**

In [1]:
#Import libraries 
import pandas as pd
import numpy as np
import sys
import sklearn
import io
import random

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns

In [2]:
#Import dataset
df_train=pd.read_csv('NSL_KDD_Train.csv')

In [3]:
#Read the train data
df_train

,Unnamed: 0,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,0,udp,other,SF,146,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,1,0,tcp,private,S0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,2,0,tcp,http,SF,232,8153,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,3,0,tcp,http,SF,199,420,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,4,0,tcp,private,REJ,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,125967,0,tcp,private,S0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,125968,8,udp,private,SF,105,145,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,125969,0,tcp,smtp,SF,2231,384,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,125970,0,tcp,klogin,S0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,125971,0,tcp,ftp_data,SF,151,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

In [4]:
# Drop the first column as it is repeated.
df_train=df_train.drop("Unnamed: 0", axis='columns' )
df_train

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,tcp,private,S0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,8,udp,private,SF,105,145,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,0,tcp,smtp,SF,2231,384,0,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,0,tcp,klogin,S0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,0,tcp,ftp_data,SF,151,0,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

In [5]:
#Import test data
df_test=pd.read_csv("NSL_KDD_Test.csv")

In [6]:
df_test

,0,tcp,private,REJ,0.1,0.2,0.3,0.4,0.5,0.6,...,10.1,0.04.1,0.06.1,0.22,0.23,0.24,0.25,1.2,1.3,neptune
0,0,tcp,private,REJ,0,0,0,0,0,0,...,1,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,86,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,57,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,86,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan
4,0,tcp,http,SF,267,14515,0,0,0,0,...,255,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22538,0,tcp,smtp,SF,794,333,0,0,0,0,...,141,0.72,0.06,0.01,0.01,0.01,0.0,0.00,0.00,normal
22539,0,tcp,http,SF,317,938,0,0,0,0,...,255,1.00,0.00,0.01,0.01,0.01,0.0,0.00,0.00,normal
22540,0,tcp,http,SF,54540,8314,0,0,0,2,...,255,1.00,0.00,0.00,0.00,0.00,0.0,0.07,0.07,back
22541,0,udp,domain_u,SF,42,42,0,0,0,0,...,252,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,normal
22542,0,tcp,sunrpc,REJ,0,0,0,0,0,0,...,21,0.08,0.03,0.00,0.00,0.00,0.0,0.44,1.00,mscan

## Check and Clean the dataset

In [7]:
#check the shape
df_train.shape

(125972, 42)

In [8]:
df=df_train

In [9]:
# Understand the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125972 entries, 0 to 125971
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125972 non-null  int64
 1   protocol_type                125972 non-null  object
 2   service                      125972 non-null  object
 3   flag                         125972 non-null  object
 4   src_bytes                    125972 non-null  int64
 5   dst_bytes                    125972 non-null  int64
 6   land                         125972 non-null  int64
 7   wrong_fragment               125972 non-null  int64
 8   urgent                       125972 non-null  int64
 9   hot                          125972 non-null  int64
 10  num_failed_logins            125972 non-null  int64
 11  logged_in                    125972 non-null  int64
 12  num_compromised              125972 non-null  int64
 13  root_shell                   125972 non-null  int64
 14  su_attempted                 125972 non-null  int64
 15  num_root                     125972 non-null  int64
 16  num_file_creations           125972 non-null  int64
 17  num_shells                   125972 non-null  int64
 18  num_access_files             125972 non-null  int64
 19  num_outbound_cmds            125972 non-null  int64
 20  is_host_login                125972 non-null  int64
 21  is_guest_login               125972 non-null  int64
 22  count                        125972 non-null  int64
 23  srv_count                    125972 non-null  int64
 24  serror_rate                  125972 non-null  float64
 25  srv_serror_rate              125972 non-null  float64
 26  rerror_rate                  125972 non-null  float64
 27  srv_rerror_rate              125972 non-null  float64
 28  same_srv_rate                125972 non-null  float64
 29  diff_srv_rate                125972 non-null  float64
 30  srv_diff_host_rate           125972 non-null  float64
 31  dst_host_count               125972 non-null  int64
 32  dst_host_srv_count           125972 non-null  int64
 33  dst_host_same_srv_rate       125972 non-null  float64
 34  dst_host_diff_srv_rate       125972 non-null  float64
 35  dst_host_same_src_port_rate  125972 non-null  float64
 36  dst_host_srv_diff_host_rate  125972 non-null  float64
 37  dst_host_serror_rate         125972 non-null  float64
 38  dst_host_srv_serror_rate     125972 non-null  float64
 39  dst_host_rerror_rate         125972 non-null  float64
 40  dst_host_srv_rerror_rate     125972 non-null  float64
 41  label                        125972 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 40.4+ MB

In [66]:
# update the column header with header list taken from the previous data info command 
df_train.columns=["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

df_test.columns=["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label"]

In [11]:
df_train

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.00,1.00,neptune
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125967,0,tcp,private,S0,0,0,0,0,0,0,...,25,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125968,8,udp,private,SF,105,145,0,0,0,0,...,244,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125969,0,tcp,smtp,SF,2231,384,0,0,0,0,...,30,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125970,0,tcp,klogin,S0,0,0,0,0,0,0,...,8,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
125971,0,tcp,ftp_data,SF,151,0,0,0,0,0,...,77,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

In [12]:
df_train.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune

In [13]:
df_test.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,private,REJ,0,0,0,0,0,0,...,1,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,86,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,57,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,86,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan
4,0,tcp,http,SF,267,14515,0,0,0,0,...,255,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal

In [14]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.0,0.00,normal
1,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.0,0.00,neptune
2,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.0,0.01,normal
3,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,normal
4,0,tcp,private,REJ,0,0,0,0,0,0,...,19,0.07,0.07,0.00,0.00,0.00,0.00,1.0,1.00,neptune

In [15]:
#Understand the label distribution in each dataset (different types of attacks)
print('Label distribution in Training set')
print(df['label'].value_counts())
print()

print('Label distribution in Training set')
print(df['label'].value_counts())
print()

Label distribution in Training set
normal             67342
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: label, dtype: int64

Label distribution in Training set
normal             67342
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: label, dtype: int64

## Step 1: Data Preprocessing

### Convert all categorical data in numerical(binary) data

I used One-Hot-Encoding to convert all categorical properties to binary properties. One_Hot-Encoding requirement, the input to this transformer must be an integer matrix expressing values taken with categorical properties. The output will be a sparse matrix in which each column corresponds to possible value.

In [16]:
# columns are categorical, protocol_type (column 2), service (column 3), flag (column 4).

print('Training set:')
for columns in df.columns:
    if df[columns].dtypes == 'object' :
        unique_cat = len(df[columns].unique())
        print("Feature '{columns}' has {unique_cat} categories".format(columns=columns, unique_cat=unique_cat))

print()
print('Distribution of categories in service:')
print(df['service'].value_counts().sort_values(ascending=False).head())

Training set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 70 categories
Feature 'flag' has 11 categories
Feature 'label' has 23 categories

Distribution of categories in service:
http        40338
private     21853
domain_u     9043
smtp         7313
ftp_data     6859
Name: service, dtype: int64

In [17]:
#Execute above steps on Test data

print('Test set:')
for col_name in df_test.columns:
    if df_test[col_name].dtypes == 'object' :
        unique_cat = len(df_test[col_name].unique())
        print("Feature '{col_name}' has {unique_cat} categories".format(col_name=col_name, unique_cat=unique_cat))

Test set:
Feature 'protocol_type' has 3 categories
Feature 'service' has 64 categories
Feature 'flag' has 11 categories
Feature 'label' has 38 categories

**From the above results we understand that there are 3 categories Protocol_type, 64 categories of service, 11 categories of flag and 38 categories of label**

### LabelEncoder

#### To change the categorical data into numerical data we shall use LabelEncoder i.e. insert data in 2D array

In [18]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
categorical_columns=['protocol_type', 'service', 'flag']

df_categorical_values = df[categorical_columns]
testdf_categorical_values = df_test[categorical_columns]

df_categorical_values.head()

  protocol_type  service flag
0           udp    other   SF
1           tcp  private   S0
2           tcp     http   SF
3           tcp     http   SF
4           tcp  private  REJ

Reference: https://github.com/Mamcose/NSL-KDD-Network-Intrusion-Detection/blob/master/NID.ipynb

In [19]:
# protocol type
unique_protocol=sorted(df.protocol_type.unique())
string1 = 'Protocol_type_'
unique_protocol2=[string1 + x for x in unique_protocol]
print(unique_protocol2)

# service
unique_service=sorted(df.service.unique())
string2 = 'service_'
unique_service2=[string2 + x for x in unique_service]
print(unique_service2)


# flag
unique_flag=sorted(df.flag.unique())
string3 = 'flag_'
unique_flag2=[string3 + x for x in unique_flag]
print(unique_flag2)


# put together
dumcols=unique_protocol2 + unique_service2 + unique_flag2


#do it for test set
unique_service_test=sorted(df_test.service.unique())
unique_service2_test=[string2 + x for x in unique_service_test]
testdumcols=unique_protocol2 + unique_service2_test + unique_flag2

['Protocol_type_icmp', 'Protocol_type_tcp', 'Protocol_type_udp']
['service_IRC', 'service_X11', 'service_Z39_50', 'service_aol', 'service_auth', 'service_bgp', 'service_courier', 'service_csnet_ns', 'service_ctf', 'service_daytime', 'service_discard', 'service_domain', 'service_domain_u', 'service_echo', 'service_eco_i', 'service_ecr_i', 'service_efs', 'service_exec', 'service_finger', 'service_ftp', 'service_ftp_data', 'service_gopher', 'service_harvest', 'service_hostnames', 'service_http', 'service_http_2784', 'service_http_443', 'service_http_8001', 'service_imap4', 'service_iso_tsap', 'service_klogin', 'service_kshell', 'service_ldap', 'service_link', 'service_login', 'service_mtp', 'service_name', 'service_netbios_dgm', 'service_netbios_ns', 'service_netbios_ssn', 'service_netstat', 'service_nnsp', 'service_nntp', 'service_ntp_u', 'service_other', 'service_pm_dump', 'service_pop_2', 'service_pop_3', 'service_printer', 'service_private', 'service_red_i', 'service_remote_job', 'service_rje', 'service_shell', 'service_smtp', 'service_sql_net', 'service_ssh', 'service_sunrpc', 'service_supdup', 'service_systat', 'service_telnet', 'service_tftp_u', 'service_tim_i', 'service_time', 'service_urh_i', 'service_urp_i', 'service_uucp', 'service_uucp_path', 'service_vmnet', 'service_whois']
['flag_OTH', 'flag_REJ', 'flag_RSTO', 'flag_RSTOS0', 'flag_RSTR', 'flag_S0', 'flag_S1', 'flag_S2', 'flag_S3', 'flag_SF', 'flag_SH']

### Converting categorical features into numbers using LabelEncoder ()

In [20]:
df_categorical_values_enc=df_categorical_values.apply(LabelEncoder().fit_transform)

print(df_categorical_values.head())
print('--------------------')
print(df_categorical_values_enc.head())

#Test data
testdf_categorical_values_enc=testdf_categorical_values.apply(LabelEncoder().fit_transform)

  protocol_type  service flag
0           udp    other   SF
1           tcp  private   S0
2           tcp     http   SF
3           tcp     http   SF
4           tcp  private  REJ
--------------------
   protocol_type  service  flag
0              2       44     9
1              1       49     5
2              1       24     9
3              1       24     9
4              1       49     1

### One-Hot-Encoding

In [21]:
enc = OneHotEncoder(categories='auto')
df_categorical_values_encenc = enc.fit_transform(df_categorical_values_enc)
df_cat_data = pd.DataFrame(df_categorical_values_encenc.toarray(),columns=dumcols)


# test set
testdf_categorical_values_encenc = enc.fit_transform(testdf_categorical_values_enc)
testdf_cat_data = pd.DataFrame(testdf_categorical_values_encenc.toarray(),columns=testdumcols)

df_cat_data.head()

,Protocol_type_icmp,Protocol_type_tcp,Protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

**Missing columns in Test set are added**

In [22]:
train_service=df['service'].tolist()
test_service=df_test['service'].tolist()
difference=list(set(train_service)-set(test_service))
string='service'
difference=[string + x for x in difference]
difference

['servicehttp_2784',
 'servicehttp_8001',
 'serviceharvest',
 'serviceaol',
 'servicered_i',
 'serviceurh_i']

In [23]:
for col in difference:
    testdf_cat_data[col]=0
    
print(df_cat_data.shape)
print(testdf_cat_data.shape)

(125972, 84)
(22543, 84)

### New numeric columns are added to main dataframe

In [24]:
df1=df.join(df_cat_data)
df1.drop('flag', axis=1, inplace=True)
df1.drop('protocol_type', axis=1, inplace=True)
df1.drop('service', axis=1, inplace=True)

# test data
df1_test=df_test.join(testdf_cat_data)
df1_test.drop('flag', axis=1, inplace=True)
df1_test.drop('protocol_type', axis=1, inplace=True)
df1_test.drop('service', axis=1, inplace=True)

print(df1.shape)
print(df1_test.shape)

(125972, 123)
(22543, 123)

**The dataset was divided into separate datasets for each attack category. Attack tags have been renamed for each. 0 = Normal, 1 = DoS, 2 = Probe, 3 = R2L, 4 = U2R. In the new datasets, the tag column has been replaced with the new values.**

In [25]:
labeldf=df1['label']
labeldf_test=df1_test['label']


# change the label column
newlabeldf=labeldf.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})
newlabeldf_test=labeldf_test.replace({ 'normal' : 0, 'neptune' : 1 ,'back': 1, 'land': 1, 'pod': 1, 'smurf': 1, 'teardrop': 1,'mailbomb': 1, 'apache2': 1, 'processtable': 1, 'udpstorm': 1, 'worm': 1,
                           'ipsweep' : 2,'nmap' : 2,'portsweep' : 2,'satan' : 2,'mscan' : 2,'saint' : 2
                           ,'ftp_write': 3,'guess_passwd': 3,'imap': 3,'multihop': 3,'phf': 3,'spy': 3,'warezclient': 3,'warezmaster': 3,'sendmail': 3,'named': 3,'snmpgetattack': 3,'snmpguess': 3,'xlock': 3,'xsnoop': 3,'httptunnel': 3,
                           'buffer_overflow': 4,'loadmodule': 4,'perl': 4,'rootkit': 4,'ps': 4,'sqlattack': 4,'xterm': 4})



# put the new label column back
df1['label'] = newlabeldf
df1_test['label'] = newlabeldf_test

In [26]:
to_drop_DoS = [0,1]
to_drop_Probe = [0,2]
to_drop_R2L = [0,3]
to_drop_U2R = [0,4]

# Filter all rows with label value except itself
# isin filter function

DoS_df=df1[df1['label'].isin(to_drop_DoS)];
Probe_df=df1[df1['label'].isin(to_drop_Probe)];
R2L_df=df1[df1['label'].isin(to_drop_R2L)];
U2R_df=df1[df1['label'].isin(to_drop_U2R)];



#test
DoS_df_test=df1_test[df1_test['label'].isin(to_drop_DoS)];
Probe_df_test=df1_test[df1_test['label'].isin(to_drop_Probe)];
R2L_df_test=df1_test[df1_test['label'].isin(to_drop_R2L)];
U2R_df_test=df1_test[df1_test['label'].isin(to_drop_U2R)];


print('Train:')
print('Dimensions of DoS:' ,DoS_df.shape)
print('Dimensions of Probe:' ,Probe_df.shape)
print('Dimensions of R2L:' ,R2L_df.shape)
print('Dimensions of U2R:' ,U2R_df.shape)
print()
print('Test:')
print('Dimensions of DoS:' ,DoS_df_test.shape)
print('Dimensions of Probe:' ,Probe_df_test.shape)
print('Dimensions of R2L:' ,R2L_df_test.shape)
print('Dimensions of U2R:' ,U2R_df_test.shape)

Train:
Dimensions of DoS: (113269, 123)
Dimensions of Probe: (78998, 123)
Dimensions of R2L: (68337, 123)
Dimensions of U2R: (67394, 123)

Test:
Dimensions of DoS: (17170, 123)
Dimensions of Probe: (12132, 123)
Dimensions of R2L: (12596, 123)
Dimensions of U2R: (9778, 123)

## Step 2 : Feature scaling

In [27]:
# Split dataframes into X and Y sets

X_DoS = DoS_df.drop('label', 1)
Y_DoS = DoS_df.label

X_Probe = Probe_df.drop('label',1)
Y_Probe = Probe_df.label

X_R2L = R2L_df.drop('label',1)
Y_R2L = R2L_df.label

X_U2R = U2R_df.drop('label',1)
Y_U2R = U2R_df.label

# test set
X_DoS_test = DoS_df_test.drop('label',1)
Y_DoS_test = DoS_df_test.label

X_Probe_test = Probe_df_test.drop('label',1)
Y_Probe_test = Probe_df_test.label

X_R2L_test = R2L_df_test.drop('label',1)
Y_R2L_test = R2L_df_test.label

X_U2R_test = U2R_df_test.drop('label',1)
Y_U2R_test = U2R_df_test.label

In [67]:
from sklearn import preprocessing

scaler1 = preprocessing.StandardScaler().fit(X_DoS)
X_DoS=scaler1.transform(X_DoS) 

scaler2 = preprocessing.StandardScaler().fit(X_Probe)
X_Probe=scaler2.transform(X_Probe)

scaler3 = preprocessing.StandardScaler().fit(X_R2L)
X_R2L=scaler3.transform(X_R2L)

scaler4 = preprocessing.StandardScaler().fit(X_U2R)
X_U2R=scaler4.transform(X_U2R) 

# test data
scaler5 = preprocessing.StandardScaler().fit(X_DoS_test)
X_DoS_test=scaler5.transform(X_DoS_test) 

scaler6 = preprocessing.StandardScaler().fit(X_Probe_test)
X_Probe_test=scaler6.transform(X_Probe_test) 

scaler7 = preprocessing.StandardScaler().fit(X_R2L_test)
X_R2L_test=scaler7.transform(X_R2L_test) 

scaler8 = preprocessing.StandardScaler().fit(X_U2R_test)
X_U2R_test=scaler8.transform(X_U2R_test)

## Classification Models

## 1. Random Forest method

**1.1. Random Forest Method for DoS**

In [34]:
# Import Random forest classifier from sklearn 


from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# create a Gaussian Classifier
clf_DoS=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y-pred = clf.predict(X_DoS_test)
clf_DoS.fit(X_DoS,Y_DoS)

y_DoS_pred=clf_DoS.predict(X_DoS_test)

In [35]:
# After training, checking the accuracy for actual and predicted values

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(Y_DoS_test,y_pred_DoS))

Accuracy: 0.5666278392545137

In [36]:
#print(metrics.classification_report
print(metrics.confusion_matrix(Y_DoS_test,y_pred_DoS))

[[9690   21]
 [7420   39]]

In [37]:
print(metrics.classification_report(Y_DoS_test,y_pred_DoS))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      9711
           1       0.65      0.01      0.01      7459

    accuracy                           0.57     17170
   macro avg       0.61      0.50      0.37     17170
weighted avg       0.60      0.57      0.41     17170

In [39]:
# Create confusion matrix
pd.crosstab(Y_DoS_test, y_DoS_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0   1
Actual attacks
0                  9674  37
1                  7429  30

**1.2. Random Forest Method for Probe**

In [40]:
# Import Random forest classifier from sklearn 


from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# create a Gaussian Classifier
clf_Probe=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y-pred = clf.predict(X_DoS_test)
clf_Probe.fit(X_Probe,Y_Probe)

y_Probe_pred=clf_Probe.predict(X_Probe_test )

In [41]:
# After training, checking the accuracy for actual and predicted values

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(Y_Probe_test ,y_Probe_pred))

Accuracy: 0.895895153313551

In [42]:
#print(metrics.classification_report
print(metrics.confusion_matrix(Y_Probe_test,y_Probe_pred))

[[9441  270]
 [ 993 1428]]

In [43]:
# Create confusion matrix
pd.crosstab(Y_Probe_test, y_Probe_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     2
Actual attacks
0                  9441   270
2                   993  1428

In [44]:
print(metrics.classification_report(Y_Probe_test,y_Probe_pred))

              precision    recall  f1-score   support

           0       0.90      0.97      0.94      9711
           2       0.84      0.59      0.69      2421

    accuracy                           0.90     12132
   macro avg       0.87      0.78      0.82     12132
weighted avg       0.89      0.90      0.89     12132

**1.3. Random Forest Method for R2L**

In [45]:
# Import Random forest classifier from sklearn 


from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# create a Gaussian Classifier
clf_R2L=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y-pred = clf.predict(X_R2L_test)
clf_R2L.fit(X_R2L,Y_R2L)

y_R2L_pred=clf_R2L.predict(X_R2L_test)

In [46]:
# After training, checking the accuracy for actual and predicted values

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(Y_R2L_test ,y_R2L_pred))

Accuracy: 0.7709590346141633

In [47]:
#print(metrics.classification_report
print(metrics.confusion_matrix(Y_R2L_test,y_R2L_pred))

[[9711    0]
 [2885    0]]

In [48]:
# Create confusion matrix
pd.crosstab(Y_R2L_test, y_R2L_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0
Actual attacks
0                  9711
3                  2885

In [49]:
print(metrics.classification_report(Y_R2L_test,y_R2L_pred))

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      9711
           3       0.00      0.00      0.00      2885

    accuracy                           0.77     12596
   macro avg       0.39      0.50      0.44     12596
weighted avg       0.59      0.77      0.67     12596

C:\Users\14439\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

**1.4. Random Forest Method for U2R**

In [51]:
# Import Random forest classifier from sklearn 


from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

# create a Gaussian Classifier
clf_U2R=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y-pred = clf.predict(X_U2R_test)
clf_U2R.fit(X_U2R,Y_U2R)

y_U2R_pred=clf_U2R.predict(X_U2R_test )

In [52]:
# After training, checking the accuracy for actual and predicted values

from sklearn import metrics
print("Accuracy:", metrics.accuracy_score(Y_U2R_test,y_U2R_pred))

Accuracy: 0.993147883002659

In [53]:
#print(metrics.classification_report
print(metrics.confusion_matrix(Y_U2R_test,y_U2R_pred))

[[9711    0]
 [  67    0]]

In [54]:
# Create confusion matrix
pd.crosstab(Y_U2R_test, y_U2R_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0
Actual attacks
0                  9711
4                    67

In [55]:
print(metrics.classification_report(Y_U2R_test,y_U2R_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      9711
           4       0.00      0.00      0.00        67

    accuracy                           0.99      9778
   macro avg       0.50      0.50      0.50      9778
weighted avg       0.99      0.99      0.99      9778

C:\Users\14439\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

## 2. KNeighbors

**2.1. KNeighbors Method for DoS**

In [56]:
# Import knearest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier

# Create KNN Classifier
knn_DoS = KNeighborsClassifier(n_neighbors=5)

# Train the model using the trainingn sets
knn_DoS.fit(X_DoS,Y_DoS)

# Predict the response for the test dataset
y_DoS_pred = knn_DoS.predict (X_DoS_test)

In [57]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_DoS_test , y_DoS_pred))

Accuracy: 0.8916132789749563

In [58]:
# Create confusion matrix
pd.crosstab(Y_DoS_test, y_DoS_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  9422   289
1                  1572  5887

**2.2. KNeighbors Method for Probe**

In [59]:
# Import knearest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier

# Create KNN Classifier
knn_Probe = KNeighborsClassifier(n_neighbors=5)

# Train the model using the trainingn sets
knn_Probe.fit(X_Probe ,Y_Probe )

# Predict the response for the test dataset
y_Probe_pred = knn_Probe.predict (X_Probe_test)

In [60]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_Probe_test, y_Probe_pred))

Accuracy: 0.8725684141114408

In [61]:
# Create confusion matrix
pd.crosstab(Y_Probe_test, y_Probe_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     2
Actual attacks
0                  9437   274
2                  1272  1149

**2.3. KNeighbors Method for R2L**

In [62]:
# Import knearest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier

# Create KNN Classifier
knn_R2L = KNeighborsClassifier(n_neighbors=5)

# Train the model using the trainingn sets
knn_R2L.fit(X_R2L,Y_R2L)

# Predict the response for the test dataset
y_R2L_pred = knn_R2L.predict (X_R2L_test)

In [63]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_R2L_test, y_R2L_pred))

Accuracy: 0.770720863766275

In [64]:
# Create confusion matrix
pd.crosstab(Y_R2L_test, y_R2L_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0  3
Actual attacks
0                  9706  5
3                  2883  2

**2.4. KNeighbors Method for U2R**

In [68]:
# Import knearest neighbors classifier model
from sklearn.neighbors import KNeighborsClassifier

# Create KNN Classifier
knn_U2R = KNeighborsClassifier(n_neighbors=5)

# Train the model using the trainingn sets
knn_U2R.fit(X_U2R,Y_U2R)

# Predict the response for the test dataset
y_U2R_pred = knn_U2R.predict (X_U2R_test)

In [69]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(Y_U2R_test, y_U2R_pred))

Accuracy: 0.9933524238085498

In [70]:
# Create confusion matrix
pd.crosstab(Y_U2R_test, y_U2R_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0  4
Actual attacks
0                  9711  0
4                    65  2

### Cross Validation: Accuracy, Precision, Recall, F-Measure

In [71]:
print(metrics.classification_report(Y_DoS_test,y_DoS_pred))
print(metrics.classification_report(Y_Probe_test,y_Probe_pred))
print(metrics.classification_report(Y_R2L_test,y_R2L_pred))
print(metrics.classification_report(Y_U2R_test,y_U2R_pred))

              precision    recall  f1-score   support

           0       0.86      0.97      0.91      9711
           1       0.95      0.79      0.86      7459

    accuracy                           0.89     17170
   macro avg       0.91      0.88      0.89     17170
weighted avg       0.90      0.89      0.89     17170

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      9711
           2       0.81      0.47      0.60      2421

    accuracy                           0.87     12132
   macro avg       0.84      0.72      0.76     12132
weighted avg       0.87      0.87      0.86     12132

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      9711
           3       0.29      0.00      0.00      2885

    accuracy                           0.77     12596
   macro avg       0.53      0.50      0.44     12596
weighted avg       0.66      0.77      0.67     12596

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      9711
           4       1.00      0.03      0.06        67

    accuracy                           0.99      9778
   macro avg       1.00      0.51      0.53      9778
weighted avg       0.99      0.99      0.99      9778

***After this point I have analyzed the data in collective fashion to compare and understand the values easily***

## Support Vector Classification

### 3.1 SVM on all the different attacks

In [72]:
from sklearn.svm import SVC

clf_SVM_DoS=SVC(kernel='linear', C=1.0, random_state=0)
clf_SVM_Probe=SVC(kernel='linear', C=1.0, random_state=0)
clf_SVM_R2L=SVC(kernel='linear', C=1.0, random_state=0)
clf_SVM_U2R=SVC(kernel='linear', C=1.0, random_state=0)


# Fit the model
clf_SVM_DoS.fit(X_DoS, Y_DoS.astype(int))
clf_SVM_Probe.fit(X_Probe, Y_Probe.astype(int))
clf_SVM_R2L.fit(X_R2L, Y_R2L.astype(int))
clf_SVM_U2R.fit(X_U2R, Y_U2R.astype(int))

SVC(kernel='linear', random_state=0)

In [73]:
Y_DoS_pred=clf_SVM_DoS.predict(X_DoS_test)

# Create confusion matrix
pd.crosstab(Y_DoS_test, Y_DoS_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  9455   256
1                  1359  6100

In [74]:
Y_Probe_pred=clf_SVM_DoS.predict(X_Probe_test)

# Create confusion matrix
pd.crosstab(Y_Probe_test, Y_Probe_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  8260  1451
2                   639  1782

In [75]:
Y_R2L_pred=clf_SVM_R2L.predict(X_R2L_test)

# Create confusion matrix
pd.crosstab(Y_R2L_test, Y_R2L_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0    3
Actual attacks
0                  9639   72
3                  2737  148

In [76]:
Y_U2R_pred=clf_SVM_DoS.predict(X_U2R_test)

# Create confusion matrix
pd.crosstab(Y_U2R_test, Y_U2R_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  6274  3437
4                    33    34

In [86]:
print("Accuracy_Dos  :", metrics.accuracy_score(Y_DoS_test, Y_DoS_pred ))
print("Accuracy_Probe:", metrics.accuracy_score(Y_Probe_test, Y_Probe_pred ))
print("Accuracy_R2L  :", metrics.accuracy_score(Y_R2L_test, Y_R2L_pred ))
print("Accuracy_U2R  :", metrics.accuracy_score(Y_U2R_test, Y_U2R_pred ))

Accuracy_Dos  : 0.8803145020384391
Accuracy_Probe: 0.8869106495219254
Accuracy_R2L  : 0.7710384248967926
Accuracy_U2R  : 0.993147883002659

In [78]:
print(metrics.classification_report(Y_DoS_test,y_DoS_pred))
print(metrics.classification_report(Y_Probe_test,y_Probe_pred))
print(metrics.classification_report(Y_R2L_test,y_R2L_pred))
print(metrics.classification_report(Y_U2R_test,y_U2R_pred))

              precision    recall  f1-score   support

           0       0.86      0.97      0.91      9711
           1       0.95      0.79      0.86      7459

    accuracy                           0.89     17170
   macro avg       0.91      0.88      0.89     17170
weighted avg       0.90      0.89      0.89     17170

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      9711
           2       0.81      0.47      0.60      2421

    accuracy                           0.87     12132
   macro avg       0.84      0.72      0.76     12132
weighted avg       0.87      0.87      0.86     12132

              precision    recall  f1-score   support

           0       0.77      1.00      0.87      9711
           3       0.29      0.00      0.00      2885

    accuracy                           0.77     12596
   macro avg       0.53      0.50      0.44     12596
weighted avg       0.66      0.77      0.67     12596

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      9711
           4       1.00      0.03      0.06        67

    accuracy                           0.99      9778
   macro avg       1.00      0.51      0.53      9778
weighted avg       0.99      0.99      0.99      9778

 ## Ensemble Learning

In [79]:
from sklearn.ensemble import VotingClassifier

clf_voting_DoS = VotingClassifier(estimators=[('rf', clf_DoS), ('knn', knn_DoS), ('svm', clf_SVM_DoS)], voting='hard')
clf_voting_Probe = VotingClassifier(estimators=[('rf', clf_Probe), ('knn', knn_Probe), ('svm', clf_SVM_Probe)], voting='hard')
clf_voting_R2L = VotingClassifier(estimators=[('rf', clf_R2L), ('knn', knn_R2L), ('svm', clf_SVM_R2L)], voting='hard')
clf_voting_U2R = VotingClassifier(estimators=[('rf', clf_U2R), ('knn', knn_U2R), ('svm', clf_SVM_U2R)], voting='hard')

clf_voting_DoS.fit(X_DoS, Y_DoS.astype(int))
clf_voting_Probe.fit(X_Probe, Y_Probe.astype(int))
clf_voting_R2L.fit(X_R2L, Y_R2L.astype(int))
clf_voting_U2R.fit(X_U2R, Y_U2R.astype(int))

VotingClassifier(estimators=[('rf', RandomForestClassifier()),
                             ('knn', KNeighborsClassifier()),
                             ('svm', SVC(kernel='linear', random_state=0))])

In [80]:
# DoS
Y_DoS_pred=clf_voting_DoS.predict(X_DoS_test)

# Create confusion matrix
pd.crosstab(Y_DoS_test, Y_DoS_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     1
Actual attacks
0                  9607   104
1                  1951  5508

In [81]:
#Probe
Y_Probe_pred=clf_voting_Probe.predict(X_Probe_test)

# Create confusion matrix
pd.crosstab(Y_Probe_test, Y_Probe_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0     2
Actual attacks
0                  9468   243
2                  1129  1292

In [82]:
# R2L
Y_R2L_pred=clf_voting_R2L.predict(X_R2L_test)

# Create confusion matrix
pd.crosstab(Y_R2L_test, Y_R2L_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0  3
Actual attacks
0                  9711  0
3                  2884  1

In [83]:
# U2R
Y_U2R_pred=clf_voting_U2R.predict(X_U2R_test)

# Create confusion matrix
pd.crosstab(Y_U2R_test, Y_U2R_pred, rownames=['Actual attacks'], colnames=['Predicted attacks'])

Predicted attacks     0
Actual attacks
0                  9711
4                    67

## Limitations and Later Work

### Later work
We can improve the Random Forest Classification using Recursive Feature Elimination. Random Forest classification is also called lazy model as it takes a lot of time to classify the data. Using RFE we can reduce the model time by only giving the features that are more relevant/significant to the classification.

## Conclusion

After applying 4 different classification Technique to our data set and from the classification report we see that all true positive and true negatives predicted in SVM are more compared to other classification report. According to our analysis SVM works very well for the DoS attacks in the data set we have. The samples required to train the models for the class attacks like Probe, R2L and U2R was very less so we can tell that all the models were overfitted. Overall, the SVM classification works very well with the data set.

## Reference
1. https://www.unb.ca/cic/datasets/nsl.html#:~:text=NSL%2DKDD%20dataset,are%20mentioned%20in%20%5B1%5D.&text=Furthermore%2C%20the%20number%20of%20records,and%20test%20sets%20are%20reasonable.
2. https://medium.com/@lasithahiranya/did-you-know-the-famous-data-set-called-nsl-kdd-293b39420c74
3. https://arxiv.org/pdf/1903.02460.pdf
4. https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
5. https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html
6. https://www.datacamp.com/community/tutorials/k-nearest-neighbor-classification-scikit-learn
7. https://www.unb.ca/cic/datasets/ddos-2019.html